---
- 
    name: Change index.php to connect to the database
    replace:
      path: /var/www/html/index.php
      regexp: '172.20.1.101'
      replace: "{{ hostvars['dbserver']['ansible_default_ipv4']['address'] }}"
